package unlar.edu.ar.paradigma.gui;

import java.awt.BorderLayout;
import java.awt.Frame;
import java.util.List;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import unlar.edu.ar.paradigma.gui.forms.FormularioEmpleado;
import unlar.edu.ar.paradigma.gui.forms.FormularioMotivo;
import unlar.edu.ar.paradigma.gui.forms.FormularioTipoAccidente;
import unlar.edu.ar.paradigma.gui.forms.FormularioZonaCuerpo;
import unlar.edu.ar.paradigma.gui.forms.GenericFormAgregar;
import unlar.edu.ar.paradigma.gui.forms.FormularioParteCuerpo;


public class Principal extends javax.swing.JFrame {
    
    
    private JDesktopPane desktopPane;
    

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        initCustomComponents(); 
        addCustomMenu();
    }

   
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmenuOpciones = new javax.swing.JMenu();
        jmiABMAccidentes = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton4.setText("jButton4");

        jButton5.setText("jButton5");

        jButton6.setText("jButton6");

        jmenuOpciones.setText("Opciones");

        jmiABMAccidentes.setText("AMB Accidentes");
        jmiABMAccidentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiABMAccidentesActionPerformed(evt);
            }
        });
        jmenuOpciones.add(jmiABMAccidentes);

        jMenuBar1.add(jmenuOpciones);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiABMAccidentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiABMAccidentesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiABMAccidentesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JMenu jmenuOpciones;
    private javax.swing.JMenuItem jmiABMAccidentes;
    // End of variables declaration//GEN-END:variables

  
    private void addCustomMenu() {
        

        JMenuBar menuBar = getJMenuBar();  // Obtiene la barra de menú existente
        JMenu menuOpciones = new JMenu("Opciones");
        
        
        for (int i = 0; i < menuBar.getMenuCount(); i++) {
            if (menuBar.getMenu(i).getText().equals("Opciones")) {
                menuOpciones = menuBar.getMenu(i);
                break;
            }
        }
        
      if (menuOpciones != null) {
            for (int i = 0; i < menuOpciones.getItemCount(); i++) {
                if (menuOpciones.getItem(i).getText().equals("AMB Accidentes")) {
                    menuOpciones.remove(i);
                    break;
                }
            }
        } else {
            menuOpciones = new JMenu("Opciones");
            menuBar.add(menuOpciones);
        }

        // Creación de ítems de menú para cada entidad
        JMenuItem menuItemEmpleado = new JMenuItem("Empleado");
        menuItemEmpleado.addActionListener(evt -> abrirFormularioEmpleado());

        JMenuItem menuItemMotivo = new JMenuItem("Motivo");
        menuItemMotivo.addActionListener(evt -> abrirFormularioMotivo());

        JMenuItem menuItemTipoAccidente = new JMenuItem("TipoAccidente");
        menuItemTipoAccidente.addActionListener(evt -> abrirFormularioTipoAccidente());

        JMenuItem menuItemParteCuerpo = new JMenuItem("ParteCuerpo");
        menuItemParteCuerpo.addActionListener(evt -> abrirFormularioParteCuerpo());

        JMenuItem menuItemZonaCuerpo = new JMenuItem("ZonaCuerpo");
        menuItemZonaCuerpo.addActionListener(evt -> abrirFormularioZonaCuerpo());

     
        // Añadir los ítems al menú de opciones
        menuOpciones.add(menuItemEmpleado);
        menuOpciones.add(menuItemMotivo);
        menuOpciones.add(menuItemTipoAccidente);
        menuOpciones.add(menuItemParteCuerpo);
        menuOpciones.add(menuItemZonaCuerpo);

        // Añadir el menú de opciones a la barra de menú existente
        if (menuBar != null) {
            menuBar.add(menuOpciones);
        } else {
            menuBar = new JMenuBar();
            menuBar.add(menuOpciones);
            setJMenuBar(menuBar);
        }
        
        setSize(800, 600);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
    }

    private void abrirFormularioEmpleado() {
    JFrame formEmpleado = new JFrame("Gestion Empleado");
    formEmpleado.setSize(600, 400);
    formEmpleado.setLocationRelativeTo(this); // Centra sobre la ventana principal
    formEmpleado.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);  // Solo cierra esta ventana
    FormularioEmpleado formularioEmpleado = new FormularioEmpleado();
    formEmpleado.add(formularioEmpleado);
    formEmpleado.setVisible(true);  // Muestra la ventana
     
    }

    private void abrirFormularioMotivo() {
       JFrame formMotivo = new JFrame("Gestion Motivo");
        formMotivo.setSize(600, 400);
        formMotivo.setLocationRelativeTo(this); // Centra sobre la ventana principal
        formMotivo.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);  // Solo cierra esta ventana
        FormularioMotivo formularioMotivo = new FormularioMotivo();
        formMotivo.add(formularioMotivo);
        formMotivo.setVisible(true);  // Muestra la ventana
    }

    private void abrirFormularioTipoAccidente() {
       JFrame formTipoAccidente = new JFrame("Gestion Tipo de Accidentes");
       formTipoAccidente.setSize(600, 400);
       formTipoAccidente.setLocationRelativeTo(this); // Centra sobre la ventana principal
       formTipoAccidente.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);  // Solo cierra esta ventana
       FormularioTipoAccidente formularioTipoAccidente = new FormularioTipoAccidente();
       formTipoAccidente.add(formularioTipoAccidente);
       formTipoAccidente.setVisible(true);  // Muestra la ventana
    }

    private void abrirFormularioZonaCuerpo() {
            JFrame formZonaCuerpo = new JFrame("Gestion Zona Cuerpos");
           formZonaCuerpo.setSize(600, 400);
           formZonaCuerpo.setLocationRelativeTo(this); // Centra sobre la ventana principal
           formZonaCuerpo.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);  // Solo cierra esta ventana
           FormularioZonaCuerpo formularioZonaCuerpo = new FormularioZonaCuerpo();
           formZonaCuerpo.add(formularioZonaCuerpo);
           formZonaCuerpo.setVisible(true);  // Muestra la ventana
    }

    private void abrirFormularioParteCuerpo() {
            JFrame formParteCuerpo = new JFrame("Gestion Parte Cuerpo");
           formParteCuerpo.setSize(600, 400);
           formParteCuerpo.setLocationRelativeTo(this); // Centra sobre la ventana principal
           formParteCuerpo.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);  // Solo cierra esta ventana
           FormularioParteCuerpo formularioParteCuerpo = new FormularioParteCuerpo();
           formParteCuerpo.add(formularioParteCuerpo);
           formParteCuerpo.setVisible(true);  // Muestra la ventana

    }

   //Modificando la tabla y botones

    private void initCustomComponents() {
        
        DefaultTableModel model = new DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Fecha Accidente", "Ubicacion", "Legajo Empleado", "Motivo", "Tipo Accidente", "IzDer"
            }
        );
        jTable2.setModel(model);
        jTable2.setPreferredScrollableViewportSize(new java.awt.Dimension(800, 400));
           jTable2.setFillsViewportHeight(true); 
        jScrollPane2.setPreferredSize(new java.awt.Dimension(800, 400)); 



        
         jButton4.setText("Agregar");
         jButton4.addActionListener(e -> {
           // Definir las columnas que se mostrarán en el formulario agregar
           List<String> columnasEmpleado = List.of("ID", "Fecha Accidente", "Ubicacion","Legajo Empleado", "Mootivo", "Tipo Accidente", "IzqDer");
            
// Crear y mostrar el formulario de agregar
            GenericFormAgregar formulario = new GenericFormAgregar(
                (Frame) SwingUtilities.getWindowAncestor(this), 
                true, 
                columnasEmpleado
            );
            formulario.setVisible(true);
          });

        jButton5.setText("Modificar");

        jButton6.setText("Eliminar");
        
        setLayout(new BorderLayout()); 
        add(jScrollPane2, BorderLayout.CENTER);
        
        revalidate();
        repaint();

    }
}
