package unlar.edu.ar.paradigma.gui;

import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.*;
import unlar.edu.ar.paradigma.controladores.AccidenteController;
import unlar.edu.ar.paradigma.controladores.SetConexion;
import unlar.edu.ar.paradigma.gui.forms.FormularioEmpleado;
import unlar.edu.ar.paradigma.gui.forms.FormularioMotivo;
import unlar.edu.ar.paradigma.gui.forms.FormularioTipoAccidente;
import unlar.edu.ar.paradigma.gui.forms.FormularioZonaCuerpo;
import unlar.edu.ar.paradigma.gui.forms.FormularioParteCuerpo;
import unlar.edu.ar.paradigma.gui.forms.abm.AddAccidente;
import unlar.edu.ar.paradigma.gui.forms.grillas.GrillaAccidentes;
import unlar.edu.ar.paradigma.objetos.AccidenteDTO;


public class Principal extends javax.swing.JFrame {
    
    private AccidenteController accidenteController;
    
    
    private JDesktopPane desktopPane;
    

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        initCustomComponents(); 
        addCustomMenu();
        
        accidenteController = new AccidenteController();
        try {
            Connection connection = SetConexion.getConnection();
            accidenteController.setConexion(connection);
        } catch (SQLException e) {
        }
        actualizarTabla();
        
    }

   
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grillaAccidentes = new unlar.edu.ar.paradigma.gui.forms.grillas.GrillaAccidentes();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmenuOpciones = new javax.swing.JMenu();
        jmiABMAccidentes = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(grillaAccidentes);
        jScrollPane2.setViewportView(jTable1);

        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setText("jButton6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jButton4)
                .addGap(87, 87, 87)
                .addComponent(jButton6)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton6))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(80, 80, 80)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(81, 81, 81)))
        );

        jmenuOpciones.setText("Opciones");

        jmiABMAccidentes.setText("AMB Accidentes");
        jmiABMAccidentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiABMAccidentesActionPerformed(evt);
            }
        });
        jmenuOpciones.add(jmiABMAccidentes);

        jMenuBar1.add(jmenuOpciones);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiABMAccidentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiABMAccidentesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiABMAccidentesActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        //eliminar hacer nashe
        int selectedRow = jTable1.getSelectedRow();
        if(selectedRow >=0){
            //Obtener el legajo del empleado
            Integer numero = (Integer) jTable1.getValueAt(selectedRow,0);
            //Confirmar la eliminacion
            int confirm = JOptionPane.showConfirmDialog(this,
                    "¿Estas seguro de que deseas eliminar al accidente con codigo" + numero + "?", 
                    "Confirmar eliminacion", JOptionPane.YES_NO_OPTION);
            if(confirm == JOptionPane.YES_OPTION){
                //Llamar al metodo en EmpleadoController para eliminar el empleado
                AccidenteDTO accidente = accidenteController.extraer(numero);
                if(accidente != null){
                    boolean eliminado = accidenteController.eliminar(accidente);
                    if(eliminado){
                        JOptionPane.showMessageDialog(this, "Accidente eliminado con exito","Exito",JOptionPane.INFORMATION_MESSAGE);
                        actualizarTabla();
                    }else{
                        JOptionPane.showMessageDialog(this, "No se encontro el accidente", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }else{
                JOptionPane.showMessageDialog(this, "Seleccione un accidente", "Warning",JOptionPane.WARNING_MESSAGE);
            }
        
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        AddAccidente registrarAccidente = new AddAccidente(this);
        registrarAccidente.setVisible(true);
      
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private unlar.edu.ar.paradigma.gui.forms.grillas.GrillaAccidentes grillaAccidentes;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenu jmenuOpciones;
    private javax.swing.JMenuItem jmiABMAccidentes;
    // End of variables declaration//GEN-END:variables

  
    private void addCustomMenu() {
        

        JMenuBar menuBar = getJMenuBar();  // Obtiene la barra de menú existente
        JMenu menuOpciones = new JMenu("Opciones");
        
        
        for (int i = 0; i < menuBar.getMenuCount(); i++) {
            if (menuBar.getMenu(i).getText().equals("Opciones")) {
                menuOpciones = menuBar.getMenu(i);
                break;
            }
        }
        
      if (menuOpciones != null) {
            for (int i = 0; i < menuOpciones.getItemCount(); i++) {
                if (menuOpciones.getItem(i).getText().equals("AMB Accidentes")) {
                    menuOpciones.remove(i);
                    break;
                }
            }
        } else {
            menuOpciones = new JMenu("Opciones");
            menuBar.add(menuOpciones);
        }

        // Creación de ítems de menú para cada entidad
        JMenuItem menuItemEmpleado = new JMenuItem("Empleado");
        menuItemEmpleado.addActionListener(evt -> abrirFormularioEmpleado());

        JMenuItem menuItemMotivo = new JMenuItem("Motivo");
        menuItemMotivo.addActionListener(evt -> abrirFormularioMotivo());

        JMenuItem menuItemTipoAccidente = new JMenuItem("TipoAccidente");
        menuItemTipoAccidente.addActionListener(evt -> abrirFormularioTipoAccidente());

        JMenuItem menuItemParteCuerpo = new JMenuItem("ParteCuerpo");
        menuItemParteCuerpo.addActionListener(evt -> abrirFormularioParteCuerpo());

        JMenuItem menuItemZonaCuerpo = new JMenuItem("ZonaCuerpo");
        menuItemZonaCuerpo.addActionListener(evt -> abrirFormularioZonaCuerpo());

     
        // Añadir los ítems al menú de opciones
        menuOpciones.add(menuItemEmpleado);
        menuOpciones.add(menuItemMotivo);
        menuOpciones.add(menuItemTipoAccidente);
        menuOpciones.add(menuItemParteCuerpo);
        menuOpciones.add(menuItemZonaCuerpo);

        // Añadir el menú de opciones a la barra de menú existente
        if (menuBar != null) {
            menuBar.add(menuOpciones);
        } else {
            menuBar = new JMenuBar();
            menuBar.add(menuOpciones);
            setJMenuBar(menuBar);
        }
        
        setSize(800, 600);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
    }

    private void abrirFormularioEmpleado() {
    JFrame formEmpleado = new JFrame("Gestion Empleado");
    formEmpleado.setSize(600, 400);
    formEmpleado.setLocationRelativeTo(this); // Centra sobre la ventana principal
    formEmpleado.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);  // Solo cierra esta ventana
    FormularioEmpleado formularioEmpleado = new FormularioEmpleado();
    formEmpleado.add(formularioEmpleado);
    formEmpleado.setVisible(true);  // Muestra la ventana
     
    }

    private void abrirFormularioMotivo() {
       JFrame formMotivo = new JFrame("Gestion Motivo");
        formMotivo.setSize(600, 400);
        formMotivo.setLocationRelativeTo(this); // Centra sobre la ventana principal
        formMotivo.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);  // Solo cierra esta ventana
        FormularioMotivo formularioMotivo = new FormularioMotivo();
        formMotivo.add(formularioMotivo);
        formMotivo.setVisible(true);  // Muestra la ventana
    }

    private void abrirFormularioTipoAccidente() {
       JFrame formTipoAccidente = new JFrame("Gestion Tipo de Accidentes");
       formTipoAccidente.setSize(600, 400);
       formTipoAccidente.setLocationRelativeTo(this); // Centra sobre la ventana principal
       formTipoAccidente.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);  // Solo cierra esta ventana
       FormularioTipoAccidente formularioTipoAccidente = new FormularioTipoAccidente();
       formTipoAccidente.add(formularioTipoAccidente);
       formTipoAccidente.setVisible(true);  // Muestra la ventana
    }

    private void abrirFormularioZonaCuerpo() {
            JFrame formZonaCuerpo = new JFrame("Gestion Zona Cuerpos");
           formZonaCuerpo.setSize(600, 400);
           formZonaCuerpo.setLocationRelativeTo(this); // Centra sobre la ventana principal
           formZonaCuerpo.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);  // Solo cierra esta ventana
           FormularioZonaCuerpo formularioZonaCuerpo = new FormularioZonaCuerpo();
           formZonaCuerpo.add(formularioZonaCuerpo);
           formZonaCuerpo.setVisible(true);  // Muestra la ventana
    }

    private void abrirFormularioParteCuerpo() {
            JFrame formParteCuerpo = new JFrame("Gestion Parte Cuerpo");
           formParteCuerpo.setSize(600, 400);
           formParteCuerpo.setLocationRelativeTo(this); // Centra sobre la ventana principal
           formParteCuerpo.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);  // Solo cierra esta ventana
           FormularioParteCuerpo formularioParteCuerpo = new FormularioParteCuerpo();
           formParteCuerpo.add(formularioParteCuerpo);
           formParteCuerpo.setVisible(true);  // Muestra la ventana

    }



    private void initCustomComponents() {
       
         jButton4.setText("Agregar");
         
        jButton6.setText("Eliminar");
        
       // Corregir vista de accidentes
        jPanel1.removeAll();
        jPanel1.setLayout(new BorderLayout());
        JScrollPane scrollPane = new JScrollPane(jTable1);
        jPanel1.add(scrollPane, BorderLayout.CENTER);
        
        setLayout(new BorderLayout());
        add(jPanel1, BorderLayout.CENTER);
        add(jPanel2, BorderLayout.SOUTH);
        
        
        revalidate();
        repaint();

    }
    
    
    private void cargarAccidentes(List<AccidenteDTO> accidentes) {
        GrillaAccidentes model = new GrillaAccidentes();
        jTable1.setModel(model);
        model.setRowCount(0);
        model.setDatos(new ArrayList<>(accidentes));

    }

    public void actualizarTabla() {
        List<AccidenteDTO> accidente = accidenteController.extraerTodo();
        // MOstrar en tabla
        if (accidente != null && !accidente.isEmpty()) {
            cargarAccidentes(accidente);
        } else {
            System.out.println("No hay accidentes");
        }

    }
}
