/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package unlar.edu.ar.paradigma.gui.forms;

import java.awt.Frame;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import unlar.edu.ar.paradigma.controladores.SetConexion;
import unlar.edu.ar.paradigma.controladores.ZonaCuerpoController;
import unlar.edu.ar.paradigma.gui.forms.grillas.GrillaZonaCuerpo;
import unlar.edu.ar.paradigma.objetos.ZonaCuerpo;
import unlar.edu.ar.paradigma.gui.forms.abm.AddZonaCuerpo;

/**
 *
 * @author lucia
 */
public class FormularioZonaCuerpo extends javax.swing.JPanel {

    private ZonaCuerpoController zonaCuerpoController;
    public FormularioZonaCuerpo() {
        initComponents();
        initCustomComponents();
        zonaCuerpoController = new ZonaCuerpoController();
        try {
            Connection connection = SetConexion.getConnection();
            zonaCuerpoController.setConexion(connection);
        } catch (SQLException e) {
            System.out.println("No se pudo establecer la conexion en Formulario");
        }
        actualizarTabla();
    }
    
    private void cargarZonasCuerpo(List<ZonaCuerpo> zonaCuerpo) {
        GrillaZonaCuerpo model = new GrillaZonaCuerpo();
        jTable1.setModel(model);
        model.setRowCount(0);
        model.setDatos(new ArrayList<>(zonaCuerpo));

        // for(Empleado empleado : empleados){
        // model.addRow(new Object[]{empleado.getLegajo(),
        // empleado.getApellido_nombre()});
        // }
    }
    
    public void actualizarTabla() {
        List<ZonaCuerpo> zonasCuerpo = zonaCuerpoController.extraerTodo();
        // MOstrar en tabla
        if (zonasCuerpo != null && !zonasCuerpo.isEmpty()) {
            cargarZonasCuerpo(zonasCuerpo);
        } else {
            System.out.println("No hay empleados");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button1 = new java.awt.Button();
        grillaZonaCuerpo = new unlar.edu.ar.paradigma.gui.forms.grillas.GrillaZonaCuerpo();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        button1.setLabel("button1");

        jTable1.setModel(grillaZonaCuerpo);
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        jButton3.setText("jButton3");

        jButton4.setText("jButton4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(54, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private unlar.edu.ar.paradigma.gui.forms.grillas.GrillaZonaCuerpo grillaZonaCuerpo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void initCustomComponents() {
        DefaultTableModel model = new DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Codigo parte cuerpo", "Izquierdo o derecho"
            }
        );
        jTable1.setModel(model);
        jTable1.setPreferredScrollableViewportSize(new java.awt.Dimension(800, 400));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(800, 400)); 

         jButton1.setText("Agregar");
           jButton1.addActionListener(e -> {
            AddZonaCuerpo addZonaCuerpo = new AddZonaCuerpo(this);
            addZonaCuerpo.setVisible(true);
               
          
          });
           
          // jButton1.addActionListener(e -> {
           // Definir las columnas que se mostrarán en el formulario agregar
          // List<String> zonaCuerpo = List.of("IzqDer", "Codigo");
            
// Crear y mostrar el formulario de agregar
            //GenericFormAgregar formulario = new GenericFormAgregar(
              //  (Frame) SwingUtilities.getWindowAncestor(this), 
                //true, 
               // zonaCuerpo
            //);
            //formulario.setVisible(true);
         // });

        jButton2.setText("Modificar");

        jButton3.setText("Eliminar");
        
        jButton4.setText("Cerrar");
        
       
        
        revalidate();
        repaint();
    }
}