/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package unlar.edu.ar.paradigma.gui.forms;


import java.awt.Frame;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import unlar.edu.ar.paradigma.controladores.EmpleadoController;
import unlar.edu.ar.paradigma.controladores.SetConexion;
import unlar.edu.ar.paradigma.gui.forms.grillas.GrillaEmpleado;
import unlar.edu.ar.paradigma.objetos.Empleado;



/**
 *
 * @author lucia
 */
public class FormularioEmpleado extends javax.swing.JPanel {
    
    private EmpleadoController empleadoController;
    /**
     * Creates new form FormularioEmpleado
     */
    public FormularioEmpleado() {
        initComponents();
        initCustomComponents();
        empleadoController = new EmpleadoController();
        try{
            Connection connection = SetConexion.getConnection();
            empleadoController.setConexion(connection);
        } catch(SQLException e){
        }
        actualizarTabla();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grillaEmpleado1 = new unlar.edu.ar.paradigma.gui.forms.grillas.GrillaEmpleado();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jTable1.setModel(grillaEmpleado1);
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");

        jButton3.setText("jButton3");

        jButton4.setText("jButton4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(54, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            RegistrarEmpleado registrarEmpleadoForm = new RegistrarEmpleado(this);
            registrarEmpleadoForm.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private unlar.edu.ar.paradigma.gui.forms.grillas.GrillaEmpleado grillaEmpleado1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void initCustomComponents() {
        
        // DefaultTableModel model = new DefaultTableModel(
          //  new Object [][] {
            //    {null, null, null, null},
              //  {null, null, null, null},
               // {null, null, null, null},
               // {null, null, null, null}
           // },
           // new String [] {
             //   "ID-Legajo", "Apellido-Nombre"
            //}
       // );
       // jTable1.setModel(model);
       // jTable1.setPreferredScrollableViewportSize(new java.awt.Dimension(800, 400));
        //ScrollPane1.setPreferredSize(new java.awt.Dimension(800, 400)); 

         jButton1.setText("Agregar");
         
        //  jButton1.addActionListener(e -> {
           // Definir las columnas que se mostrarán en el formulario agregar
          /// List<String> columnasEmpleado = List.of("ID-Legajo", "Apellido-Nombre");
            
// Crear y mostrar el formulario de agregar
            //GenericFormAgregar formulario = new GenericFormAgregar(
              //  (Frame) SwingUtilities.getWindowAncestor(this), 
                //true, 
               // columnasEmpleado
            //);
            //formulario.setVisible(true);
         // });
          
          
          
            jButton2.addActionListener(e -> {
           // Definir las columnas que se mostrarán en el formulario agregar
           List<String> columnasEmpleado = List.of("ID-Legajo", "Apellido-Nombre");
            
// Crear y mostrar el formulario de agregar
            GenericFormModificar formulario = new GenericFormModificar(
                (Frame) SwingUtilities.getWindowAncestor(this), 
                true, 
                columnasEmpleado
            );
            formulario.setVisible(true);
          });
            
        jButton2.setText("Modificar");

        jButton3.setText("Eliminar");
        
        jButton4.setText("Cerrar");
        
       
        
        revalidate();
        repaint();
    }
    
    private void cargarEmpleados(List<Empleado> empleados){
        GrillaEmpleado model = new GrillaEmpleado();
        jTable1.setModel(model);
        model.setRowCount(0);
        model.setDatos(new ArrayList<>(empleados));
        
        //for(Empleado empleado : empleados){
          //  model.addRow(new Object[]{empleado.getLegajo(), empleado.getApellido_nombre()});
       // }
    }
    
    public void actualizarTabla(){
            List<Empleado> empleados = empleadoController.extraerTodo();
            //MOstrar en tabla
           if(empleados !=null && !empleados.isEmpty()){
              cargarEmpleados(empleados);
           }else{
                System.out.println("No hay empleados");
           }
         
    }
    
}
