/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package unlar.edu.ar.paradigma.gui.forms;

import javax.swing.*;
import java.awt.*;
import java.util.List;


public class GenericFormModificar extends javax.swing.JDialog {

    private List<String>columnNames;
    
    public GenericFormModificar(java.awt.Frame parent, boolean modal, List<String>columnNames) {
        super(parent, modal);
        initComponents();
        this.columnNames = columnNames;
        initCustomComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenericFormModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenericFormModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenericFormModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenericFormModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                 List<String> columnas = List.of("ID", "Nombre", "Apellido");  //cambiara supuestamente
                GenericFormModificar dialog = new GenericFormModificar(new JFrame(), true, columnas);
                dialog.setVisible(true);
                    }
                });
               
            }
     

    private void initCustomComponents() {
         
        JPanel formPanel = new JPanel();
         formPanel.setLayout(new GridLayout(columnNames.size(), 2, 10, 10)); // Configura el layout
           // Creación de etiquetas y campos de texto según los nombres de columna
        for (String columnName : columnNames) {
         JLabel label = new JLabel(columnName);
        JTextField textField = new JTextField();
        formPanel.add(label);
        formPanel.add(textField);
    }
        
          // Panel para los botones
        JPanel buttonsPanel = new JPanel(new FlowLayout(FlowLayout.CENTER));
        JButton btnGuardar = new JButton("Guardar");
        JButton btnCancelar = new JButton("Cancelar");
        
        buttonsPanel.add(btnGuardar);
        buttonsPanel.add(btnCancelar);
        
           // Añadir el panel de campos y el panel de botones al formulario principal
        setLayout(new BorderLayout());
        add(formPanel, BorderLayout.CENTER);
        add(buttonsPanel, BorderLayout.SOUTH);

        // Configuración de ventana
        setTitle("Modificar Registro");
        setSize(400, 300);
        setLocationRelativeTo(null);
        
         btnCancelar.addActionListener(e -> dispose());
         btnGuardar.addActionListener(e -> {
            

            // Lógica de guardado (ej. enviar los valores de los JTextFields a la base de datos)
            
            
            JOptionPane.showMessageDialog(this, "Datos Modificados correctamente.");
            dispose(); // Cerrar el formulario después de guardar
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
