/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package unlar.edu.ar.paradigma.gui.forms;

/**
 *
 * @author Dilan
 */
public class GestionAccidentes extends javax.swing.JInternalFrame {

    /**
     * Creates new form GestionAccidentes
     */
    public GestionAccidentes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtGrilla = new javax.swing.JTable();
        jtbNuevo = new javax.swing.JToggleButton();
        jtbCerrar = new javax.swing.JToggleButton();
        jtbModificar = new javax.swing.JToggleButton();
        jtbEliminar = new javax.swing.JToggleButton();

        jtGrilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtGrilla);

        jtbNuevo.setText("Nuevo");
        jtbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbNuevoActionPerformed(evt);
            }
        });

        jtbCerrar.setText("Cerrar");
        jtbCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbCerrarActionPerformed(evt);
            }
        });

        jtbModificar.setText("Modificar");
        jtbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbModificarActionPerformed(evt);
            }
        });

        jtbEliminar.setText("Eliminar");
        jtbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtbNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtbModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtbEliminar)
                        .addGap(77, 77, 77)
                        .addComponent(jtbCerrar)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtbNuevo)
                    .addComponent(jtbCerrar)
                    .addComponent(jtbModificar)
                    .addComponent(jtbEliminar))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtbNuevoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jtbNuevoActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jtbNuevoActionPerformed

    private void jtbModificarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jtbModificarActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jtbModificarActionPerformed

    private void jtbEliminarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jtbEliminarActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jtbEliminarActionPerformed

    private void jtbCerrarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jtbCerrarActionPerformed
        this.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtGrilla;
    private javax.swing.JToggleButton jtbCerrar;
    private javax.swing.JToggleButton jtbEliminar;
    private javax.swing.JToggleButton jtbModificar;
    private javax.swing.JToggleButton jtbNuevo;
    // End of variables declaration//GEN-END:variables
}
