/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package unlar.edu.ar.paradigma.gui.forms.abm;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import unlar.edu.ar.paradigma.controladores.SetConexion;
import unlar.edu.ar.paradigma.controladores.ZonaCuerpoController;
import unlar.edu.ar.paradigma.gui.forms.FormularioZonaCuerpo;
import unlar.edu.ar.paradigma.objetos.ZonaCuerpo;

/**
 *
 * @author Dilan
 */
public class AddZonaCuerpo extends javax.swing.JFrame {

    private ZonaCuerpoController zonaCuerpoController;
    private FormularioZonaCuerpo formularioZonaCuerpo;
    
    public AddZonaCuerpo(FormularioZonaCuerpo formularioZonaCuerpo) {
        this.formularioZonaCuerpo = formularioZonaCuerpo;
        initComponents();
        
        zonaCuerpoController = new ZonaCuerpoController();
        try {
            Connection connection = SetConexion.getConnection();
            zonaCuerpoController.setConexion(connection);
        } catch (SQLException e) {
            System.err.println("Error al establecer la conexión: " + e.getMessage());
        }
        
        // Carga las opciones para el combo box de ZonaCuerpo
        String[] opcionesZonaCuerpo = {"Izquierda", "Derecha"};
        jcbZonaCuerpo.setModel(new DefaultComboBoxModel<>(opcionesZonaCuerpo));
        
        // Carga las opciones para el combo box de ParteCuerpo
        List<String> partesCuerpo = zonaCuerpoController.obtenerParteCuerpo();
        DefaultComboBoxModel<String> modeloPartesCuerpo = new DefaultComboBoxModel<>();
        for (String parte : partesCuerpo) {
            modeloPartesCuerpo.addElement(parte);
        }
        jcbParteCuerpo.setModel(modeloPartesCuerpo);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbAceptar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jcbZonaCuerpo = new javax.swing.JComboBox<>();
        jcbParteCuerpo = new javax.swing.JComboBox<>();
        jlParteCuerpo = new javax.swing.JLabel();
        jlZonaCuerpo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbAceptar.setText("Aceptar");
        jbAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAceptarActionPerformed(evt);
            }
        });

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jcbZonaCuerpo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jcbParteCuerpo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jlParteCuerpo.setText("Parte:");

        jlZonaCuerpo.setText("Zona:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlZonaCuerpo)
                            .addComponent(jlParteCuerpo))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jcbParteCuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbZonaCuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbAceptar)
                        .addGap(34, 34, 34)
                        .addComponent(jbCancelar)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlZonaCuerpo)
                    .addComponent(jcbZonaCuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlParteCuerpo)
                    .addComponent(jcbParteCuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAceptar)
                    .addComponent(jbCancelar))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAceptarActionPerformed
        ZonaCuerpo zonaCuerpoObj = new ZonaCuerpo();
        
        String zonaCuerpo = jcbZonaCuerpo.getSelectedItem().toString();
        String parteCuerpo = jcbParteCuerpo.getSelectedItem().toString();
        
        int idParteCuerpo = zonaCuerpoController.obtenerIdParteCuerpo(parteCuerpo);
        int izquierdaDerecha = zonaCuerpo.equals("Izquierda") ? 0 : 1;
        
        int idZona = zonaCuerpoController.obtenerNuevoIdZona();
                
        zonaCuerpoObj.setId_zona(idZona);
        zonaCuerpoObj.setCodigo(idParteCuerpo);
        zonaCuerpoObj.setIzqder(izquierdaDerecha);
    
        
        if (zonaCuerpoController.crear(zonaCuerpoObj)) {
        System.out.println("Zona cuerpo creada exitosamente.");
        // Actualizar la tabla solo si formularioZonaCuerpo no es null
        if (formularioZonaCuerpo != null) {
            formularioZonaCuerpo.actualizarTabla();
        }
        } else {
            System.out.println("Hubo un error al crear la zona cuerpo.");
        }
        
        this.dispose();
    }//GEN-LAST:event_jbAceptarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jcbZonaCuerpoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbZonaCuerpoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbZonaCuerpoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddZonaCuerpo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddZonaCuerpo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddZonaCuerpo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddZonaCuerpo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormularioZonaCuerpo formulariioZonaCuerpo = new FormularioZonaCuerpo();
                new AddZonaCuerpo(formulariioZonaCuerpo).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAceptar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JComboBox<String> jcbParteCuerpo;
    private javax.swing.JComboBox<String> jcbZonaCuerpo;
    private javax.swing.JLabel jlParteCuerpo;
    private javax.swing.JLabel jlZonaCuerpo;
    // End of variables declaration//GEN-END:variables
}
