package unlar.edu.ar.paradigma.gui.forms.abm;

import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import unlar.edu.ar.paradigma.controladores.SetConexion;
import unlar.edu.ar.paradigma.controladores.ZonaCuerpoController;
import unlar.edu.ar.paradigma.gui.forms.FormularioZonaCuerpo;
import unlar.edu.ar.paradigma.objetos.ZonaCuerpo;

public class ModZonaCuerpo extends javax.swing.JFrame {
    
    
   private ZonaCuerpo zonaCuerpo;
    private ZonaCuerpoController zonaCuerpoController;
     private FormularioZonaCuerpo formularioZonaCuerpo;

    /**
     * Creates new form ModZonaCuerpo
     */
    public ModZonaCuerpo(ZonaCuerpo zonaCuerpo,FormularioZonaCuerpo formularioZonaCuerpo) {
        this.formularioZonaCuerpo = formularioZonaCuerpo;
        initComponents();
        
        zonaCuerpoController = new ZonaCuerpoController();
        try {
            Connection connection = SetConexion.getConnection();
            zonaCuerpoController.setConexion(connection);
        } catch (SQLException e) {
            System.err.println("Error al establecer la conexión: " + e.getMessage());
        }
         this.zonaCuerpo = zonaCuerpo;
        cargarDatosZonaCuerpo();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlModificarZonaCuerpo = new java.awt.Label();
        jlId_zona = new javax.swing.JLabel();
        jlZonaCuerpo = new javax.swing.JLabel();
        jtfId_zona = new javax.swing.JTextField();
        jtfZonaCuerpo = new javax.swing.JTextField();
        jbModificar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jlParteCuerpo = new javax.swing.JLabel();
        jtfParteCuerpo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlModificarZonaCuerpo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jlModificarZonaCuerpo.setName(""); // NOI18N
        jlModificarZonaCuerpo.setPreferredSize(new java.awt.Dimension(50, 30));
        jlModificarZonaCuerpo.setText("Modificar ZonaCuerpo");

        jlId_zona.setText("ID:");

        jlZonaCuerpo.setText("Zona del cuerpo:");

        jtfId_zona.setEditable(false);
        jtfId_zona.setEnabled(false);

        jtfZonaCuerpo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfZonaCuerpoActionPerformed(evt);
            }
        });

        jbModificar.setText("Modificar");
        jbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarActionPerformed(evt);
            }
        });

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jlParteCuerpo.setText("Parte del cuerpo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbModificar)
                            .addComponent(jlZonaCuerpo)
                            .addComponent(jlId_zona)
                            .addComponent(jlParteCuerpo))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtfZonaCuerpo, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                    .addComponent(jtfId_zona, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfParteCuerpo)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jbCancelar))))
                    .addComponent(jlModificarZonaCuerpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jlModificarZonaCuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlId_zona)
                    .addComponent(jtfId_zona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfZonaCuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlZonaCuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlParteCuerpo)
                    .addComponent(jtfParteCuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbModificar)
                    .addComponent(jbCancelar))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarDatosZonaCuerpo() {
        jtfId_zona.setText(String.valueOf(zonaCuerpo.getId_zona()));
        jtfZonaCuerpo.setText(String.valueOf(zonaCuerpo.getCodigo()));
        jtfParteCuerpo.setText(String.valueOf(zonaCuerpo.getIzqder()));
    }
    
    
    private void jtfZonaCuerpoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfZonaCuerpoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfZonaCuerpoActionPerformed

    private void jbModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarActionPerformed
        zonaCuerpo.setId_zona(Integer.valueOf(jtfId_zona.getText()));
        zonaCuerpo.setCodigo(Integer.valueOf(jtfZonaCuerpo.getText()));
        zonaCuerpo.setIzqder(Integer.valueOf(jtfParteCuerpo.getText()));
        boolean exito = zonaCuerpoController.modificar(zonaCuerpo);
        if (exito) {
            JOptionPane.showMessageDialog(this, "ZonaCuerpo actualizada con éxito", "Exito", JOptionPane.INFORMATION_MESSAGE);
            formularioZonaCuerpo.actualizarTabla();
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Error al actualizar la ZonaCuerpo", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbModificarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jbCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModZonaCuerpo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModZonaCuerpo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModZonaCuerpo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModZonaCuerpo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbModificar;
    private javax.swing.JLabel jlId_zona;
    private java.awt.Label jlModificarZonaCuerpo;
    private javax.swing.JLabel jlParteCuerpo;
    private javax.swing.JLabel jlZonaCuerpo;
    private javax.swing.JTextField jtfId_zona;
    private javax.swing.JTextField jtfParteCuerpo;
    private javax.swing.JTextField jtfZonaCuerpo;
    // End of variables declaration//GEN-END:variables
}
